on:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-20.04
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release Urlaubsverwaltung Test
          body_path: .chglog/1.1.1.md
