# Trigger the workflow on milestone events
on:
  push

name: Release Notes
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_MILESTONE_TITLE: "true"
      - name: Show fs
        run: ls -la
      - name: Show fs2
        run: cat ${{ github.event.milestone.title }}.md
      - name: Add something at the end
        run: sed -i '1 i\anything' ${{ github.event.milestone.title }}.md
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test-${{ github.event.milestone.title }}
          release_name: Release Test ${{ github.event.milestone.title }}
          draft: true
          body_path: "./${{ github.event.milestone.title }}.md"
      - name: add tag
        run: git tag -l "test-${{ github.event.milestone.title }}"
      - name: push tag
        run: git push --follow-tags
